import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/lib/ReactQueryProvider";
import ClientProvider from "@/components/ClientProvider";
import { ThemeProvider } from "@/components/theme-provider";

import PersistUserInfoState from "@/components/persist-user-state";

import Modal from "@/components/modal";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientProvider>
        <ReactQueryProvider>

          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}

          >
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <PersistUserInfoState />
              {children}

              <Modal />
            </ThemeProvider>
          </body>


        </ReactQueryProvider>
      </ClientProvider>
    </html>
  );
}
